name: "ikuuu automatic check"

on:
  schedule:
    - cron: "8 0 * * *"

jobs:
  run-start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run start
        run: |
          python main.py